# Generated by Django 3.2.7 on 2021-10-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
    ]
