# Generated by Django 3.2.7 on 2021-11-06 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0003_auto_20211027_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
