# Generated by Django 3.2.7 on 2021-11-13 03:38

from django.db import migrations, models
import theBlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[(theBlog.models.UserDetail.GenderChoices['Male'], 'Male'), (theBlog.models.UserDetail.GenderChoices['Female'], 'Female'), (theBlog.models.UserDetail.GenderChoices['Other'], 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='religion',
            field=models.CharField(blank=True, choices=[(theBlog.models.UserDetail.ReligionChoices['Christianity'], 'Christianity'), (theBlog.models.UserDetail.ReligionChoices['Islam'], 'Islam'), (theBlog.models.UserDetail.ReligionChoices['Atheist'], 'Atheist'), (theBlog.models.UserDetail.ReligionChoices['Hinduism'], 'Hinduism'), (theBlog.models.UserDetail.ReligionChoices['Buddhism'], 'Buddhism'), (theBlog.models.UserDetail.ReligionChoices['Ethnic'], 'Ethnic'), (theBlog.models.UserDetail.ReligionChoices['Other'], 'Other')], max_length=20, null=True),
        ),
    ]
