# Generated by Django 3.2.7 on 2021-12-06 03:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0006_alter_userdetail_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_Video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.ManyToManyField(blank=True, related_name='PostTag', to='theBlog.tag'),
        ),
    ]
