# Generated by Django 3.2.7 on 2021-12-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0007_auto_20211206_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
