# Generated by Django 3.2.7 on 2021-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0008_auto_20211209_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
