# Generated by Django 3.2.7 on 2021-12-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0009_auto_20211209_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theBlog.category'),
        ),
    ]
