# Generated by Django 3.2.7 on 2022-02-01 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0010_alter_post_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='blocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
